apiVersion: 2

providers:
  - name: 'default_alert_provisioner'
    orgId: 1
    folder: order-tracker
    type: file
    options:
      path: /etc/grafana/provisioning/alerts/json
      foldersFromFilesStructure: false
